### PR TITLE
Add unused_use,extra_empty_lines fixture test.

### PR DESCRIPTION
**Pull request by SpacePossum**
some fixtures for https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1571 ^-^

### CODE REVIEW

**Comment by SpacePossum** [comment]
ping @keradus :)
I won't be added any new fixture tests soon so please let me know you've seen this ;)

**Comment by SpacePossum** [comment]
btw. the coverage test needs some tweaking I think, adding a test should not be counting as decreasing ;)

**Comment by keradus** [comment]
pong @SpacePossum 
I saw this, thanks ;)

**Comment by keradus** [comment]
You were 2 minutes faster than me !
Could you send your own PR for original repository ?

**Comment by SpacePossum** [comment]
ha! oh man, two commits almost at the same time, than two comments almost at the same time :D 
thanks for taking care of this :+1:

**Pull request closed without merging**
